name: Test Workflow

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Hello
        run: echo "Hello from GitHub Actions 🎉"
