name: Manual Trigger Workflow

# 👇 Trigger: manual run
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your name'
        required: true
        default: 'Sanketh'

jobs:
  greet_user:
    runs-on: ubuntu-latest

    steps:
      - name: Print greeting
        run: echo "Hello ${{ inputs.name }} from manual trigger!"
