name: Push Workflow

# 👇 Trigger: when code is pushed to main branch
on:
  push:
    branches:
      - main

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print greeting
        run: echo "Hello, GitHub Actions!"
